###############################################################################
#   @author         :   Trent Stanton
#   @date           :   19/05/2019
#   @package        :   Downlights
#   @description    :   Automations inc. Auto Entryway Light, Auto Entry Light
#   @url            :   
###############################################################################
homeassistant:
  customize:
    switch.diningroom_light:
      icon: mdi:lightbulb
    switch.kitchen_light:
      icon: mdi:lightbulb
    switch.entry_light:
      icon: mdi:lightbulb
    switch.entryway_light:
      icon: mdi:lightbulb
input_boolean:
  disable_entry_light_person_detected:
    name: Disable Entry Light When Person Detected
    initial: off
    icon: mdi:home
  disable_entryway_light_frontdoor:
    name: Disable Entryway Light When Frontdoor Open
    initial: off
    icon: mdi:home
  disable_entry_light_frontdoor:
    name: Disable Entry Light When Frontdoor Open
    initial: off
    icon: mdi:home
  disable_livingroom_light_frontdoor:
    name: Disable Living Room Light When Frontdoor Open
    initial: off
    icon: mdi:home
scene:
  - name: Living Room Light Full
    entities:
      light.livingroom:
        state: true
        brightness_pct: '100'
  - name: Living Room Light Dim
    entities:
      light.livingroom:
        state: true
        brightness_pct: '5'

###############################################################################
#                               Automations
###############################################################################
automation:

  - alias: Entry Light Front Door Person Detected
    trigger:
      - platform: numeric_state
        entity_id:
          - image_processing.tensorflow_frontdoor
        above: '0'
    condition:
      condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: -0:30:00
      - condition: state
        entity_id: switch.entry_light
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_entry_light_person_detected
        state: 'off'
    action:
    - service: switch.turn_on
      entity_id: switch.entry_light
    - delay: '00:01:00'
    - service: switch.turn_off
      entity_id: switch.entry_light

  - alias: Entry Light Front Door Opens
    trigger:
    - platform: state 
      entity_id: binary_sensor.door_frontdoor
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: -0:30:00
      - condition: state
        entity_id: switch.entry_light
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_entry_light_frontdoor
        state: 'off'
    action:
    - service: switch.turn_on
      entity_id: switch.entry_light
    - delay: '00:02:00'
    - service: switch.turn_off
      entity_id: switch.entry_light

  - alias: Entryway Light Front Door Opens
    trigger:
    - platform: state 
      entity_id: binary_sensor.door_frontdoor
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: -0:30:00
      - condition: state
        entity_id: switch.entryway_light
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_entryway_light_frontdoor
        state: 'off'
    action:
    - service: switch.turn_on
      entity_id: switch.entryway_light
    - delay: '00:02:00'
    - service: switch.turn_off
      entity_id: switch.entryway_light
      
  - alias: Living Room Light Arriving Front Door
    trigger:
    - platform: state 
      entity_id: binary_sensor.door_frontdoor
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: -0:30:00
      - condition: state
        entity_id: light.livingroom
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_livingroom_light_frontdoor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.fibaro_motion_sensor_sensor
        state: 'off'
        for:
          minutes: 10
      - condition: state
        entity_id: binary_sensor.motion_hallway
        state: 'off'
        for:
          minutes: 10
    action:
    - service: light.turn_on
      entity_id: light.livingroom