###############################################################################
#   @author         :   Trent Stanton
#   @date           :   11/10/2019
#   @package        :   
#   @description    :   Controls Downloads Within Network
#   @url            :   
###############################################################################
homeassistant:
  customize:
    switch.nzbget_pause:
      friendly_name: NZBGet Pause Downloads
      icon: 'mdi:pause-circle'
    sensor.nzbget_download_rate:
      friendly_name: Current NZBGet Speed
      icon: 'mdi:download'

input_boolean:
  disable_nzbget_unpause_schedule:
    name: Disable NZBGet Unpause Schedule
    icon: 'mdi:download'

nzbget:
  host: !secret nzbget_ipaddress
  port: !secret nzbget_port
  username: !secret nzbget_username
  password: !secret nzbget_password

switch:
  - platform: template
    switches:
      nzbget_pause:
        value_template: "{{ is_state('sensor.nzbget_download_paused', 'True') }}"
        turn_on:
          service: nzbget.pause
        turn_off:
          service: nzbget.resume

# Old Configuration - Depreciated by HA NZBGet component.
#switch:
#  - platform: command_line
#    switches:
## Control via API & Curl Commands
#      nzbget_pause:
#        command_on: !secret nzbget_pause_switch_on
#        command_off: !secret nzbget_pause_switch_off
#        command_state: !secret nzbget_pause_switch_state

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: 'Unpause Downloads in the Evening'
    trigger:
      - platform: time
        at: '23:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.disable_nzbget_unpause_schedule
        state: 'off'
    action:
    - service: switch.turn_off
      entity_id: switch.nzbget_pause
  - alias: 'Pause NZBGet Downloads when Streaming'
    trigger:
      - platform: state
        entity_id: sensor.living_room_tv_source
        to: '9Now'
      - platform: state
        entity_id: sensor.living_room_tv_source
        to: 'ABC iview'
      - platform: state
        entity_id: sensor.living_room_tv_source
        to: 'Amazon Prime Video'
      - platform: state
        entity_id: sensor.living_room_tv_source
        to: 'Netflix'
      - platform: state
        entity_id: sensor.living_room_tv_source
        to: 'SBS on Demand'
      - platform: state
        entity_id: sensor.living_room_tv_source
        to: 'YouTube'
    action:
    - service: switch.turn_on
      entity_id: switch.nzbget_pause